-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgbj9LbePk3WOalNg7
msWnn/f8LcxY2knPlXxiPZoiFJSgCgYIKoZIzj0DAQehRANCAAQ5EkeM1KWXsFRP
mrs8Wmx3NheRF+56v+F51ARMPfjDdnm5AUZK3C/gW/F7Q3MR9J+UW7jxFmStrVzp
SJsWiOpr
-----END PRIVATE KEY-----